### ISSUE TITLE
[Feature request] Add HDR support

### ISSUE THREAD

**Issue by CarterLi** [jesec/iina#2]
MacBook Pro 2021 has support of HDR, but sadly IINA doesn't support it.

There's a fork repo to add HDR support in IINA: https://github.com/anastasiuspernat/iina

How about merge it?

---

I have tried myself but the CI stuck with `Can't find any online and idle self-hosted runner in the current repository, account/organization that matches the required labels: 'macos-arm64'
Waiting for a self-hosted runner to pickup this job...`

Have no idea how to resolve it

**Comment by jesec** [comment]
Do you really have HDR contents? 

It would look horrible to force HDR, and play SDR contents. 

Additionally, to ensure proper rendering, you would need to set the colorSpace of the display to match the video. 

---

You need to have a `macos-arm64` machine configured as a self-hosted GitHub actions runner. You can also use the Xcode to build manually, or simply download the compiled package from artifacts.

**Comment by CarterLi** [comment]
> Do you really have HDR contents?

Youtube has a lot.

> 
> It would look horrible to force HDR, and play SDR contents.

It's detected dynamically

https://github.com/anastasiuspernat/iina/blob/911cb118e66e805b2c41244edfa27d241a204be2/iina/VideoView.swift#L233

> 
> Additionally, to ensure proper rendering, you would need to set the colorSpace of the display to match the video.
> 

[--target-trc=pq](https://mpv.io/manual/master/#options-target-trc) should do that.

Why not have a try for it. We can easy revert back if it doesn't work properly.

**Comment by jesec** [comment]
I ported the commit. It is obvious that it is implemented incorrectly.

A simple QuickTime comparison shows that the gamma curve is incorrect, resulting in the loss of details.

**Comment by CarterLi** [comment]
Yes I tested it too.

The HDR specific code did run though...
